<?php

/* $filename= 'http://www.lsbags.co.uk/images/thumbnails/600/600/detailed/15/LS0054A1-BROWN_%283%29_mb3c-eh.jpg';
$file_headers = @get_headers($filename);

if($file_headers[0] == 'HTTP/1.0 404 Not Found'){
      echo "The file $filename does not exist";
} else if ($file_headers[0] == 'HTTP/1.0 302 Found' && $file_headers[7] == 'HTTP/1.0 404 Not Found'){
    echo "The file $filename does not exist, and I got redirected to a custom 404 page..";
} else {
    echo "The file $filename exists";
}
 */
/* $image_url = 'http://www.lsbags.co.uk/images/thumbnails/600/600/detailed/15/LS0054A-BROWN_%283%29_mb3c-eh.jpg';
							// $image_url=$img->src;
							$content = file_get_contents($image_url);
						//Store in the filesystem.
						$imgpath="media/test/".time()."image.jpg";
						$fp = fopen($imgpath,"w");
						fwrite($fp, $content);
						fclose($fp); */ 
						
	
/*  $_category = Mage::getResourceModel('catalog/category_collection')
        ->addFieldToFilter('name','Women high heels')
        ->getFirstItem();

echo $categoryId = $_category->getId();
$category = Mage::getModel('catalog/category')->load($categoryId);

$catnames = array();
$catids = array();
foreach ($category->getParentCategories() as $parent) {
    $catnames[] = $parent->getName();
	$catids[] = $parent->getId();
} 					
print_r($catids); */


						/* $xx='';
						
						$categoryarray=array_unique($catids);
						foreach($categoryarray as $ct)
						{
							
							$xx.=$ct.',';
						}
						 $xx=substr($xx, 0, -1); 
						
						$pieces = explode(",",$xx);		
					    print_r($pieces); */

$error="";
$insert='';
$update='';
$error2="";
$ext222='';
$copy="";

if(isset($_FILES['file_uplod']['name']) && ($_FILES['file_uplod']['name'] != ''))
     {

         $filename = $_FILES['file_uplod']['name'];
       $ext = pathinfo($filename, PATHINFO_EXTENSION);
        if( $ext !== 'csv')
			{
			
			$error[]='Please Upload CSV File!';
			
			}
		else{
       $uploader = new Varien_File_Uploader('file_uplod');
	   $uploader->setAllowedExtensions(array('text/csv'));
     
       $path = realpath($_FILES["file"]["tmp_name"]);
       $file = $path."/csvupload/".$_FILES['file_uplod']['name'];
		  //$uploader->save($path.'csvupload', $_FILES['file_uplod']['name']);
		  
		  if(move_uploaded_file($_FILES['file_uplod']['tmp_name'],$file)) 
		  {

				 //Insert into your db

				 //$fp = fopen($target, "r");
				  $csv = new Varien_File_Csv();
                  $data = $csv->getData($file);
	  
			}
		  
		  
	    // print_r($data);
			 
			  //exit;
			//first line are the headers
			$headers = $data[0];
			$allProductData = array();
			for($i=1; $i<count($data); $i++){
			  $productData = array();
			  foreach ($headers as $index=>$attributeCode) {
				  $productData[$attributeCode] = $data[$i][$index];
				  
				  //echo $data[$i]['Filename'];exit;
				}
			  $allProductData[] = $productData;
			}
			//echo "<pre>";print_r($allProductData);exit;
			//unlink($file);
		  
		  foreach($allProductData as $product_info)
		  {
			  

			  
			 
				  //echo $product_info['Filename'];
				       Mage::app()->setCurrentStore(Mage_Core_Model_App::ADMIN_STORE_ID);
						$product = Mage::getModel('catalog/product');
				        if(!$product->getIdBySku($product_info['Filename']))
						{
							// echo "<pre>";print_r($product_info); 
						$product
						//    ->setStoreId(1) //you can set data in store scope
							->setWebsiteIds(array(1)) //website ID the product is assigned to, as an array
							->setAttributeSetId(4) //ID of a attribute set named 'default'
							->setTypeId('simple') //product type
							->setCreatedAt(strtotime('now')) //product creation time
						//    ->setUpdatedAt(strtotime('now')) //product update time
						 
							->setSku($product_info['Filename']) //SKU
							->setName($product_info['Description']) //product name
							->setWeight(0.0000)
							->setStatus(1) //product status (1 - enabled, 2 - disabled)
							->setTaxClassId(0) //tax class (0 - none, 1 - default, 2 - taxable, 4 - shipping)
							->setVisibility(Mage_Catalog_Model_Product_Visibility::VISIBILITY_BOTH) //catalog and search visibility
							->setPrice($product_info['Selling Price'])
							->setPricePerItem($product_info['Selling Price']);
							
							//$product->setDescription($drp_product->description)
							$product->setDescription($product_info['Description'])
							->setShortDescription($product_info['Description']);
						 
						    // $image_url = 'media/csvproduct/'.$product_info['Image'];
							// $image_url = 'media/csvproduct/'.$product_info['Filename'].'.jpg';
							/* // $image_url=$img->src;
							$content = file_get_contents($image_url);
						//Store in the filesystem.
						$imgpath="media/Csvproduct/".time()."image.jpg";
						$fp = fopen($imgpath,"w");
						fwrite($fp, $content);
						fclose($fp); */
						
						
						//$product->addImageToMediaGallery($image_url, array('image','thumbnail','small_image'), false, false) ;
						// unlink($image_url);
						
						  			 // if (file_exists($product_info['Link'])) 
										 if ($product_info['Link']!='N/A') 
									  {
										  
										  
										  
											 
											 $image_url=$product_info['Link'];  
												$content = file_get_contents($image_url);
											//Store in the filesystem.
											$imgpath="media/csvproduct/".time()."image.jpg";
											$fp = fopen($imgpath,"w");
											fwrite($fp, $content);
											fclose($fp);
											$product->addImageToMediaGallery($imgpath, array('image','thumbnail','small_image'), false, false) ;
											//unlink($imgpath); 
											
											
											
										} else {
											 $image_url = 'media/csvproduct/'.$product_info['Filename'].'.jpg';
							if (file_exists($image_url)) {
								$product->addImageToMediaGallery($image_url, array('image','thumbnail','small_image'), false, false) ;
							    //unlink($image_url);
							
							 }
										}
						
						
						   
						
						$product->setStockData(array(
											   'use_config_manage_stock' => 0, //'Use config settings' checkbox
											   'manage_stock'=>1, //manage stock
											   'min_sale_qty'=>1, //Minimum Qty Allowed in Shopping Cart
											   'max_sale_qty'=>2, //Maximum Qty Allowed in Shopping Cart
											   'is_in_stock' => 1, //Stock Availability
											   'qty' => $product_info['Quantity'] //qty
										   )
							);
						 
						//$product->setCategoryIds(array(316)); //assign product to categories
						$_category = Mage::getResourceModel('catalog/category_collection')
									->addFieldToFilter('name',$product_info['Category'])
									->getFirstItem();

							 $categoryId = $_category->getId();
							$category = Mage::getModel('catalog/category')->load($categoryId);

							//$catnames = array();
							$catids = array();
							foreach ($category->getParentCategories() as $parent) {
								//$catnames[] = $parent->getName();
								$catids[] = $parent->getId();
							}
							$product->setCategoryIds($catids);
							
						
						
						$product->save();
						$insert[0]=1;

						}
						else{
							
							$product_update = Mage::getModel('catalog/product')->loadByAttribute('sku',$product_info['Filename']);
						 $product_update
							->setName($product_info['Description'])
							->setStatus(1) //product status (1 - enabled, 2 - disabled)
							->setTaxClassId(0)
							->setPrice($product_info['Selling Price'])
							->setPricePerItem($product_info['Selling Price']);
							
							
							
							//$product_update->setDescription($drp_product->description)
							$product_update->setDescription($product_info['Description'])
							->setShortDescription($product_info['Description']);
						 
							
							$stockItem = Mage::getModel('cataloginventory/stock_item')->loadByProduct($product_update->getId());
							$stockItem->setData('is_in_stock',1); //set updated data as your requirement
							$stockItem->setData('qty',$product_info['Quantity']); //set updated quantity 
							$stockItem->setData('manage_stock',1);
							$stockItem->setData('use_config_notify_stock_qty',1);
							
							//$image_url = 'media/csvproduct/'.$product_info['Image'];
							/* $image_url = 'media/csvproduct/'.$product_info['Filename'].'.jpg';
							if (file_exists($image_url)) {
								$product_update->addImageToMediaGallery($image_url, array('image','thumbnail','small_image'), false, false) ;
							//unlink($image_url);
							
							} */
							
							
								
							$_category = Mage::getResourceModel('catalog/category_collection')
									->addFieldToFilter('name',$product_info['Category'])
									->getFirstItem();

							 $categoryId = $_category->getId();
							$category = Mage::getModel('catalog/category')->load($categoryId);

							//$catnames = array();
							$catids = array();
							foreach ($category->getParentCategories() as $parent) {
								//$catnames[] = $parent->getName();
								$catids[] = $parent->getId();
							}
							$product_update->setCategoryIds($catids);
							
							$stockItem->save();

							$product_update->save();
							
							$update[0]=1;
							
						}
		  }
		  
		 //echo "<pre>" ; print_r($allProductData); 
		} 
	 }
?>

    <?php
define ("MAX_SIZE","5000"); 
function getExtension($str)
{
         $i = strrpos($str,".");
         if (!$i) { return ""; }
         $l = strlen($str) - $i;
         $ext = substr($str,$i+1,$l);
         return $ext;
}

$errors=0;

if(isset($_POST['sendfiles'])) 
{
  $uploaddir = "media/csvproduct/"; //a directory inside
    foreach ($_FILES['photos']['name'] as $name => $value)
    {
        $filename = stripslashes($_FILES['photos']['name'][$name]);
     //get the extension of the file in a lower case format
          $extension = getExtension($filename);
         $extension = strtolower($extension);
         // echo "\n This is the extension: ",$extension;
        // if (($extension != "jpg") && ($extension != "jpeg") && ($extension != "png") && ($extension != "gif")) 
			 if (($extension != "jpg")) 
         { 
        //print error message
        ?>
           
          <?php
             $ext222[]=1;
         }
        else
        {
            $size=filesize($_FILES['photos']['tmp_name'][$name]);
            /* if ($size > MAX_SIZE*1024)
            {
            ?>
               <h4>You have exceeded the size limit!</h4>
              <?php
                $errors=1;
            } */
            //$image_name=$filename.'.'.$extension;
			$image_name=$filename;
             $newname="media/csvproduct/".$image_name;
            $copied = copy($_FILES['photos']['tmp_name'][$name], $newname);
            if (!$copied) 
            {
                ?>
                <h4>Copy unsuccessfull!</h4>
                <?php
                $errors2[]="not coppy";
            }
			else
			{
				$copy[]=" coppy";
			}

        }

    } 
    //echo "Images uploaded successfully";
}
//mysql_close($dbhandle);
?>
<div style="padding: 10px 10px 10px 10px;border: 1px solid #dacdcd;">       
<?php if(!empty($error)){?><p style="color:red;">Please upload CSV File!</p><?php }?>
	<?php if(!empty($insert)){?><p style="color:green;">Product Inserted Successfully</p><?php }?>
	<?php if(!empty($update)){?><p style="color:green;">Product Updated Successfully</p><?php }?>
	<?php if(!empty($error2)){?><p style="color:green;">Image copy Error</p><?php }?>
	<?php if(!empty($ext222)){?><p style="color:green;">Only Jpg image support</p><?php }?>
	<?php if(!empty($copy)){?><p style="color:green;">Product Image Copy Successfully</p><?php }?>
	
	

<div class="tab">
  <button class="tablinks active" onclick="openCity(event, 'imageupload')">Upload Images</button>
  <button class="tablinks" onclick="openCity(event, 'csvupload')">Upload CSV</button>
 </div>

<div id="imageupload" class="tabcontent" style="display:block;">
 
<form method="post" action="" enctype="multipart/form-data">
<input type="hidden" name="MAX_FILE_SIZE" value="500000">
 <p><h3>Upload Images:</h3></p>
<!--<input multiple="true" onchange="this.form.submit()" type="file" name="photos[]"/>-->
<input multiple="true" type="file" name="photos[]" required/>
<!--<input type="hidden" name="sendfiles" value="Send Files" />  -->
<input type="submit" value="Upload" name="sendfiles" style="color: white;background-color: #42a2ce;color: black;padding: 6px;border-radius: 6px;">
</form>

</div>

<div id="csvupload" class="tabcontent">

<form  method="post" enctype="multipart/form-data">
   <p><h3>Upload CSV File:</h3></p>
    <input type="file" name="file_uplod" id="fileToUpload" required>
    <input type="submit" value="Upload" name="submit" style="color: white;background-color: #42a2ce;color: black;padding: 6px;border-radius: 6px;">
	
</form>
</div>



<style>
body {font-family: "Lato", sans-serif;}

/* Style the tab */
div.tab {
    overflow: hidden;
    border: 1px solid #ccc;
    background-color: #f1f1f1;
}

/* Style the buttons inside the tab */
div.tab button {
    background-color: inherit;
    float: left;
    border: none;
    outline: none;
    cursor: pointer;
    padding: 14px 16px;
    transition: 0.3s;
    font-size: 17px;
}

/* Change background color of buttons on hover */
div.tab button:hover {
    background-color: #ddd;
}

/* Create an active/current tablink class */
div.tab button.active {
    background-color: #ccc;
}

/* Style the tab content */
.tabcontent {
    display: none; 
    padding: 6px 12px;
    border: 1px solid #ccc;
    border-top: none;
}
</style>
<script>
//openCity('event', 'imageupload');
function openCity(evt, cityName) {
    var i, tabcontent, tablinks;
    tabcontent = document.getElementsByClassName("tabcontent");
    for (i = 0; i < tabcontent.length; i++) {
        tabcontent[i].style.display = "none";
    }
    tablinks = document.getElementsByClassName("tablinks");
    for (i = 0; i < tablinks.length; i++) {
        tablinks[i].className = tablinks[i].className.replace(" active", "");
    }
    document.getElementById(cityName).style.display = "block";
    evt.currentTarget.className += " active";
}
</script>



</div>